steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/app-juneboku-xyz:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/app-juneboku-xyz:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'app-juneboku-xyz', '--image', 'gcr.io/$PROJECT_ID/app-juneboku-xyz:$COMMIT_SHA', '--region', 'asia-northeast1', '--allow-unauthenticated']
options:
  logging: CLOUD_LOGGING_ONLY
